version: "#{build}"

image:
  - Visual Studio 2019

configuration:
  - coverage
  - official

cache:
  - windeployqt64releaseonly.zip -> appveyor.yml
  - FlexBison.zip -> appveyor.yml
  - CGAL-Setup.exe -> appveyor.yml
  - gmp-all-CGAL-3.9.zip -> appveyor.yml
  - mpfr-all-CGAL-3.9.zip -> appveyor.yml
  - asciidoc.zip -> appveyor.yml
  - src-highlite.zip -> appveyor.yml
  - csharp.lang -> appveyor.yml

install:
  - set CGAL_DIR=C:\CGAL\
  - set GMP=%CGAL_DIR%\auxiliary\gmp
  - set BOOST_ROOT=C:\Libraries\boost_1_73_0
  - set QTDIR=C:\Qt\5.15.1\mingw81_64
  - set ASCIIDOC=C:\asciidoc-8.6.10
  - set SOURCEHIGHLIGHT=C:\source-highlight
  - set PATH=%PATH%;C:\Qt\Tools\mingw810_64\bin
  # install patched windeployqt
  - if not exist windeployqt64releaseonly.zip
      appveyor DownloadFile http://tripleboot.org/Uploads/windeployqt64releaseonly.zip
  - 7z x -o%QTDIR%\bin windeployqt64releaseonly.zip
  # Install Flex/Bison
  - if not exist FlexBison.zip
      appveyor DownloadFile https://downloads.sourceforge.net/project/winflexbison/win_flex_bison-latest.zip
      -FileName FlexBison.zip
  - 7z x -o%QTDIR%\bin FlexBison.zip
  # Install CGAL
  - if not exist CGAL-Setup.exe
      appveyor DownloadFile https://github.com/CGAL/cgal/releases/download/v5.1/CGAL-5.1-Setup.exe
      -FileName CGAL-Setup.exe
  - if not exist %CGAL_DIR%
      CGAL-Setup.exe /S /D=c:\CGAL
  # Patch CGAL
  - patch -l %CGAL_DIR%\include\CGAL\Nef_S2\SM_overlayer.h < patch\Fix-use-of-uninitialized-variable-in-SM_overlayer.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\IO\File_scanner_OFF.h < patch\Fix-use-of-uninitialized-variable-in-File_scanner_OFF.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\IO\File_writer_OFF.h < patch\Fix-uninitialized-member-in-File_writer_OFF.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\IO\File_writer_VRML_2.h < patch\Fix-uninitialized-member-in-File_writer_VRML_2.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\internal\Triangulation_ds_iterators_3.h < patch\Fix-uninitialized-member-in-Triangulation_ds_iterators_3.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Triangulation_2\internal\Triangulation_line_face_circulator_2.h < patch\Fix-uninitialized-member-in-Triangulation_line_face_circulator_2.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Triangulation_3.h < patch\Fix-uninitialized-member-in-Triangulation_3.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Tools\chained_map.h < patch\Fix-uninitialized-member-in-chained_map.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Nef_3\ID_support_handler.h < patch\Performance-in-ID_support_handler.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Nef_3\K3_tree.h < patch\Fix-uninitialized-member-in-K3_tree.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\GMP\Gmpz_type.h < patch\Fix-uninitialized-member-in-Gmpz_type.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\GMP\Gmpfr_type.h < patch\Fix-uninitialized-member-in-Gmpfr_type.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Multiset.h < patch\Fix-uninitialized-members-in-Multiset.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Convex_decomposition_3\Single_wall_creator.h < patch\Fix-uninitialized-member-in-Single_wall_creator.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Convex_decomposition_3\Edge_sorter.h < patch\Fix-uninitialized-member-in-Edge_sorter.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Convex_decomposition_3\Ray_hit_generator2.h < patch\Fix-uninitialized-members-in-Ray_hit_generator2.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Nef_3\SNC_io_parser.h < patch\Fix-uninitialized-member-in-SNC_io_parser.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Nef_3\Volume.h < patch\Fix-uninitialized-member-in-Volume.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Polyhedron_incremental_builder_3.h < patch\Fix-uninitialized-member-in-Polyhedron_incremental_builder.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Triangulation_vertex_base_with_info_2.h < patch\Fix-uninitialized-member-in-Triangulation_vertex_base_with_info_2.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\utility.h < patch\Fix-uninitialized-members-in-utility.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\boost\graph\iterator.h < patch\Fix-uninitialized-member-in-iterator.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Straight_skeleton_2\Straight_skeleton_builder_events_2.h < patch\Fix-uninitialized-member-in-Straight_skeleton_builder_events_2.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Filtered_predicate.h < patch\Fix-uninitialized-member-in-Filtered_predicate.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Intersections_2\Segment_2_Segment_2.h < patch\Fix-uninitialized-member-in-Segment_2_Segment_2.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Nef_3\Vertex.h < patch\Fix-dereference-after-null-check-in-Nef_3-Vertex.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Nef_3\SNC_io_parser.h < patch\Fix-passing-big-parameters-by-value-in-SNC_io_parser.patch
  - patch -l %CGAL_DIR%\include\CGAL\Nef_2\debug.h < patch\Fix-warning-cgal-nef-debug.patch
  - patch -l %CGAL_DIR%\include\CGAL\assertions.h < patch\Add-a-destructor-assertion-catch-macro.patch
  - patch -l %CGAL_DIR%\include\CGAL\Nef_3\K3_tree.h < patch\Fix-uncaught-exception-in-K3_tree.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\IO\VRML_2_ostream.h < patch\Fix-uncaught-exception-in-VRML_2_ostream.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Nef_S2\Sphere_map.h < patch\Fix-uncaught-exception-in-Sphere_map.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Nef_polyhedron_S2.h < patch\Fix-uncaught-exception-in-Nef_polyhedron_S2.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Nef_3\SNC_point_locator.h < patch\Fix-uncaught-exception-in-SNC_point_locator.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Handle_for.h < patch\Fix-uncaught-exception-in-Handle_for.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Straight_skeleton_2\Straight_skeleton_aux.h < patch\Add-noexcept-to-Ref_counted_base-in-Straight_skeleton_aux.h.patch
  - patch -l %CGAL_DIR%\include\CGAL\Nef_3\SNC_io_parser.h < patch\Add-bounds-checks-in-SNC_io_parser.h.patch
  # Install GMP
  - if not exist gmp-all-CGAL-3.9.zip
      appveyor DownloadFile https://cgal.geometryfactory.com/CGAL/precompiled_libs/auxiliary/x64/GMP/5.0.1/gmp-all-CGAL-3.9.zip
  - 7z x -o%GMP% gmp-all-CGAL-3.9.zip -aoa
  # Install MPFR
  - if not exist mpfr-all-CGAL-3.9.zip
      appveyor DownloadFile https://cgal.geometryfactory.com/CGAL/precompiled_libs/auxiliary/x64/MPFR/3.0.0/mpfr-all-CGAL-3.9.zip
  - 7z x -o%GMP% mpfr-all-CGAL-3.9.zip -aoa
  # Install asciidoc
  - if not exist asciidoc.zip
      appveyor DownloadFile https://github.com/asciidoc/asciidoc/archive/8.6.10.zip
      -FileName asciidoc.zip
  - 7z x -oC:\ asciidoc.zip
  # Install source-highlight
  - if not exist src-highlite.zip
      appveyor DownloadFile https://downloads.sourceforge.net/project/gnuwin32/src-highlite/2.1.2/src-highlite-2.1.2-bin.zip
      -FileName src-highlite.zip
  - 7z x -o%SOURCEHIGHLIGHT% src-highlite.zip
  - mv %SOURCEHIGHLIGHT%\bin\source-highlight.exe %SOURCEHIGHLIGHT%\bin\source-highlight-exe.exe
  - cp %APPVEYOR_BUILD_FOLDER%\scripts\source-highlight.bat %SOURCEHIGHLIGHT%\bin
  - if not exist csharp.lang
      appveyor DownloadFile https://www.gnu.org/software/src-highlite/lang_files/csharp.lang
      -FileName csharp.lang
  - cp csharp.lang %SOURCEHIGHLIGHT%\share\source-highlight
  - set LANGMAP=%SOURCEHIGHLIGHT%\share\source-highlight\lang.map
  - echo. >> %LANGMAP%
  - echo csharp = csharp.lang >> %LANGMAP%
  # Setup environment
  - set PATH=%PATH%;%CGAL_DIR%\bin
  - set PATH=%PATH%;%SOURCEHIGHLIGHT%\bin
  - set PATH=%PATH%;%CGAL_DIR%\auxiliary\gmp\lib
  - set PATH=%PATH%;%QTDIR%\bin
  - set PATH=C:\Program Files\Git\usr\bin;%PATH%

for:
-
  matrix:
    only:
      - configuration: coverage
  build_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - qmake CONFIG+=coverage
    - mingw32-make -j4 -f Makefile.Release
    - windeployqt64releaseonly
        --no-svg
        --no-translations
        --no-angle
        --release
        release/rapcad.exe
  test_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - release\rapcad.exe -t test
-
  matrix:
    only:
      - configuration: official
  branches:
    only:
      - master
  build_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - set /p VERSION=<VERSION
    - qmake CONFIG+=official
    - mingw32-make -j4 -f Makefile.Release
    - mingw32-make clean
    - mingw32-make user_guide.html
    - cp user_guide.html release
    - cp
        %GMP%\lib\libgmp-10.dll
        %GMP%\lib\libmpfr-4.dll
        release
    - windeployqt64releaseonly
        --no-svg
        --no-translations
        --no-angle
        --release
        release/rapcad.exe
    - rm -r release/imageformats
    - makensis installer.nsi
    - mv rapcad_setup.exe rapcad_%VERSION%_setup.exe
    - mv release rapcad_%VERSION%
    - 7z a -tzip rapcad_%VERSION%.zip rapcad_%VERSION%
  artifacts:
    - path: rapcad_*_setup.exe
      name: RapCAD Installer
    - path: rapcad_*.zip
      name: RapCAD Binaries
